<!-- Copyright (C) 2017 Diana Corbacho

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>. -->
---
title: "Species"
output: html_document
---

```{r, echo=FALSE}
species.name <- species_df[, sp]
```

### `r species.name`

```{r, echo=FALSE, include=FALSE}
# Extract the data
species.data <- data[data$Species==sp,]
forearm <- na.omit(as.numeric(as.character(species.data$Forearm)))
weight <- na.omit(as.numeric(as.character(species.data$Weight)))
male <- species.data[species.data$Sex=="M",]
female <- species.data[species.data$Sex=="F",]
```

A total of `r nrow(species.data)` `r species.name` were captured in `r length(unique(droplevels(species.data$Location)))` locations: `r lapply(unique(droplevels(species.data$Location)), function(x) sites[sites$Location == as.character(x), 2])`.

```{r, echo=FALSE}
# Plot summary table
f <- c(min(forearm), max(forearm), mean(forearm), median(forearm), quantile(forearm, prob = c(0.25, 0.75)))
w <- c(min(weight), max(weight), mean(weight), median(weight), quantile(weight, prob = c(0.25, 0.75)))
measures <- rbind(f,w)
rownames(measures) <- c("Forearm", "Weight")
colnames(measures) <- c("Min", "Max", "Mean", "Median", "1st Qu.", "3rd Qu.")
kable(measures)
```

```{r, echo=FALSE}
# Plot sex ratio table
df <- rbind(c((nrow(male)/nrow(female)) * 100, nrow(male), nrow(female)))
colnames(df) <- c("Sex ratio", "Male", "Female")
rownames <- NULL
kable(df)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
# Extract data for scatterplot
correlation <- cbind(as.numeric(as.character(species.data$Weight)), as.numeric(as.character(species.data$Forearm)))
correlation <- correlation[complete.cases(correlation),]
```
```{r, echo=FALSE}
# Plot scatterplot
plot(correlation, pch = 16, cex = 1.3, col = "blue", xlab="Weight (g)", ylab="Forearm (mm)", main=paste0(species.name, ": forearm vs weight"))
abline(lm(correlation[,2] ~ correlation[,1]))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Plot histogram of forearm distribution
df <- data.frame(
  sex=species.data$Sex,
  forearm=as.numeric(as.character(species.data$Forearm))
)
df <- df[complete.cases(df),]

ggplot(df, aes(x=forearm), title=species.name) + 
  geom_histogram(aes(y=..density..), colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666") +
  labs(title=paste0(species.name, ": forearm distribution")) + xlab("Forearm (m)") + ylab("Frequency")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Plot histogram of forearm distribution by sex
mu <- ddply(df, "sex", summarise, grp.mean=mean(forearm))

p<-ggplot(df, aes(x=forearm, color=sex)) +
  xlab("Forearm (mm)") + ylab("Count") + 
  geom_histogram(fill="white", position="dodge") +
  geom_vline(data=mu, aes(xintercept=grp.mean, color=sex),
             linetype="dashed")+
  theme(legend.position="top")+
  labs(title=paste0(species.name, ": forearm distribution by sex"))
p+scale_color_brewer(palette="Dark2")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Plot histogram of weight distribution
df <- data.frame(
  sex=species.data$Sex,
  weight=as.numeric(as.character(species.data$Weight))
)
df <- df[complete.cases(df),]

ggplot(df, aes(x=weight), title=species.name) + 
  geom_histogram(aes(y=..density..), colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666") +
  labs(title=paste0(species.name, ": weight distribution")) + xlab("Weight (g)") + ylab("Frequency")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Plot histogram of weight distribution by sex
mu <- ddply(df, "sex", summarise, grp.mean=mean(weight))

p<-ggplot(df, aes(x=weight, color=sex)) +
  xlab("Weight (g)") + ylab("Count") + 
  geom_histogram(fill="white", position="dodge") +
  geom_vline(data=mu, aes(xintercept=grp.mean, color=sex),
             linetype="dashed")+
  theme(legend.position="top")+
  labs(title=paste0(species.name, ": weight distribution by sex"))
p+scale_color_brewer(palette="Dark2")
```

****